# Generated by Django 5.0.3 on 2024-03-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='app/images/product/sprit.png', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DC', 'Coke'), ('CH', 'Cherry'), ('ZS', 'Zero'), ('EN', 'Energy'), ('LI', 'Lime'), ('VA', 'Vanilla'), ('SP', 'Sprite'), ('FA', 'Fanta')], max_length=2),
        ),
    ]
