# Generated by Django 5.0.3 on 2024-03-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_product_image_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('LI', 'Lime'), ('ZS', 'Zero'), ('VA', 'Vanilla'), ('DC', 'Coke'), ('CH', 'Cherry'), ('SP', 'Sprite'), ('EN', 'Energy')], max_length=2),
        ),
    ]
