# Generated by Django 5.0.3 on 2024-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EN', 'Energy'), ('FA', 'Fanta'), ('SP', 'Sprite'), ('VA', 'Vanilla'), ('CH', 'Cherry'), ('ZS', 'Zero'), ('LI', 'Lime'), ('DC', 'Coke')], max_length=2),
        ),
    ]
