# Generated by Django 5.0.3 on 2024-03-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EN', 'Energy'), ('DC', 'Coke'), ('FA', 'Fanta'), ('ZS', 'Zero'), ('LI', 'Lime'), ('VA', 'Vanilla'), ('CH', 'Cherry'), ('SP', 'Sprite')], max_length=2),
        ),
    ]
