# Generated by Django 5.0.3 on 2024-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_category_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DC', 'Coke'), ('LI', 'Lime'), ('SP', 'Sprite'), ('CH', 'Cherry'), ('FA', 'Fanta'), ('EN', 'Energy'), ('VA', 'Vanilla'), ('ZS', 'Zero')], max_length=2),
        ),
    ]
