# Generated by Django 5.0.3 on 2024-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('EN', 'Energy'), ('DC', 'Coke'), ('LI', 'Lime'), ('SP', 'Sprite'), ('ZS', 'Zero'), ('VA', 'Vanilla'), ('CH', 'Cherry')], max_length=2),
        ),
    ]
