# Generated by Django 5.0.3 on 2024-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SP', 'Sprite'), ('EN', 'Energy'), ('VA', 'Vanilla'), ('FA', 'Fanta'), ('LI', 'Lime'), ('CH', 'Cherry'), ('ZS', 'Zero'), ('DC', 'Coke')], max_length=2),
        ),
    ]
