# Generated by Django 5.0.3 on 2024-03-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VA', 'Vanilla'), ('ZS', 'Zero'), ('EN', 'Energy'), ('SP', 'Sprite'), ('DC', 'Coke'), ('CH', 'Cherry'), ('FA', 'Fanta'), ('LI', 'Lime')], max_length=2),
        ),
    ]
