# Generated by Django 5.0.3 on 2024-03-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CH', 'Cherry'), ('LI', 'Lime'), ('EN', 'Energy'), ('DC', 'Coke'), ('VA', 'Vanilla'), ('FA', 'Fanta'), ('SP', 'Sprite'), ('ZS', 'Zero')], max_length=2),
        ),
    ]
