# Generated by Django 5.0.3 on 2024-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LI', 'Lime'), ('FA', 'Fanta'), ('CH', 'Cherry'), ('VA', 'Vanilla'), ('EN', 'Energy'), ('SP', 'Sprite'), ('ZS', 'Zero'), ('DC', 'Coke')], max_length=2),
        ),
    ]
