# Generated by Django 5.0.3 on 2024-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VA', 'Vanilla'), ('FA', 'Fanta'), ('SP', 'Sprite'), ('ZS', 'Zero'), ('LI', 'Lime'), ('DC', 'Coke'), ('CH', 'Cherry'), ('EN', 'Energy')], max_length=2),
        ),
    ]
