# Generated by Django 5.0.3 on 2024-04-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LI', 'Lime'), ('ZS', 'Zero'), ('EN', 'Energy'), ('CH', 'Cherry'), ('VA', 'Vanilla'), ('FA', 'Fanta'), ('SP', 'Sprite'), ('DC', 'Coke')], max_length=2),
        ),
    ]
