# Generated by Django 5.0.3 on 2024-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VA', 'Vanilla'), ('RB', 'Red Bull'), ('SP', 'Sprite'), ('CS', 'Capri-Sun'), ('LI', 'Lime'), ('CH', 'Cherry'), ('MR', 'Monster'), ('FA', 'Fanta'), ('NS', 'Nestlé'), ('7U', '7UP'), ('DR', 'Dr-Pepper'), ('ZS', 'Zero'), ('CO', 'Coca-Cola'), ('PS', 'Pepsi'), ('DC', 'Coke'), ('EN', 'Energy')], max_length=2),
        ),
    ]
