# Generated by Django 5.0.3 on 2024-04-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CH', 'Cherry'), ('RB', 'Red Bull'), ('FA', 'Fanta'), ('CO', 'Coca-Cola'), ('CS', 'Capri-Sun'), ('DC', 'Coke'), ('VA', 'Vanilla'), ('SP', 'Sprite'), ('DR', 'Dr-Pepper'), ('PS', 'Pepsi'), ('7U', '7UP'), ('LI', 'Lime'), ('MR', 'Monster'), ('NS', 'Nestlé'), ('EN', 'Energy'), ('ZS', 'Zero')], max_length=2),
        ),
    ]
