# Generated by Django 5.0.3 on 2024-04-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PS', 'Pepsi'), ('SP', 'Sprite'), ('RB', 'Red Bull'), ('NS', 'Nestlé'), ('CO', 'Coca-Cola'), ('FA', 'Fanta'), ('DR', 'Dr-Pepper'), ('MR', 'Monster'), ('7U', '7UP'), ('BS', 'Bisleri')], max_length=2),
        ),
    ]
