# Generated by Django 5.0.3 on 2024-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CO', 'Coca-Cola'), ('RB', 'Red Bull'), ('PS', 'Pepsi'), ('DR', 'Dr-Pepper'), ('SP', 'Sprite'), ('FA', 'Fanta'), ('MR', 'Monster'), ('7U', '7UP'), ('BS', 'Bisleri'), ('MD', 'Mountain Dew')], max_length=2),
        ),
    ]
