# Generated by Django 5.0.3 on 2024-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('SP', 'Sprite'), ('MD', 'Mountain Dew'), ('PS', 'Pepsi'), ('CO', 'Coca-Cola'), ('DR', 'Dr-Pepper'), ('RB', 'Red Bull'), ('MR', 'Monster'), ('7U', '7UP')], max_length=2),
        ),
    ]
