# Generated by Django 5.0.3 on 2024-04-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Dr-Pepper'), ('7U', '7UP'), ('BS', 'Bisleri'), ('PS', 'Pepsi'), ('CO', 'Coca-Cola'), ('FA', 'Fanta'), ('MR', 'Mirinda'), ('RB', 'Red Bull'), ('SP', 'Sprite'), ('MD', 'Mountain Dew')], max_length=2),
        ),
    ]
