# Generated by Django 5.0.3 on 2024-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BS', 'Bisleri'), ('SP', 'Sprite'), ('PS', 'Pepsi'), ('7U', '7UP'), ('DR', 'Dr-Pepper'), ('RB', 'Red Bull'), ('FA', 'Fanta'), ('MD', 'Mountain Dew'), ('MR', 'Mirinda'), ('CO', 'Coca-Cola')], max_length=2),
        ),
    ]
