# Generated by Django 5.0.3 on 2024-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('7U', '7UP'), ('DR', 'Dr-Pepper'), ('MR', 'Mirinda'), ('SP', 'Sprite'), ('FA', 'Fanta'), ('MD', 'Mountain Dew'), ('RB', 'Red Bull'), ('BS', 'Bisleri'), ('PS', 'Pepsi'), ('CO', 'Coca-Cola')], max_length=2),
        ),
    ]
