# Generated by Django 5.0.3 on 2024-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('7U', '7UP'), ('CO', 'Coca-Cola'), ('SP', 'Sprite'), ('MD', 'Mountain Dew'), ('RB', 'Red Bull'), ('DR', 'Dr-Pepper'), ('MR', 'Mirinda'), ('BS', 'Bisleri'), ('FA', 'Fanta'), ('PS', 'Pepsi')], max_length=2),
        ),
    ]
