# Generated by Django 5.0.3 on 2024-05-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('MR', 'Mirinda'), ('BS', 'Bisleri'), ('PS', 'Pepsi'), ('SP', 'Sprite'), ('RB', 'Red Bull'), ('MD', 'Mountain Dew'), ('CO', 'Coca-Cola'), ('DR', 'Dr-Pepper'), ('7U', '7UP')], max_length=2),
        ),
    ]
