# Generated by Django 5.0.3 on 2024-05-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SP', 'Sprite'), ('FA', 'Fanta'), ('DR', 'Dr-Pepper'), ('BS', 'Bisleri'), ('7U', '7UP'), ('CO', 'Coca-Cola'), ('MD', 'Mountain Dew'), ('PS', 'Pepsi'), ('RB', 'Red Bull'), ('MR', 'Mirinda')], max_length=2),
        ),
    ]
