# Generated by Django 5.0.3 on 2024-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('DR', 'Dr-Pepper'), ('MR', 'Mirinda'), ('SP', 'Sprite'), ('MD', 'Mountain Dew'), ('BS', 'Bisleri'), ('7U', '7UP'), ('PS', 'Pepsi'), ('CO', 'Coca-Cola'), ('RB', 'Red Bull')], max_length=2),
        ),
    ]
