# Generated by Django 5.0.3 on 2024-05-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('7U', '7UP'), ('MR', 'Mirinda'), ('CO', 'Coca-Cola'), ('FA', 'Fanta'), ('PS', 'Pepsi'), ('DR', 'Dr-Pepper'), ('RB', 'Red Bull'), ('BS', 'Bisleri'), ('MD', 'Mountain Dew'), ('SP', 'Sprite')], max_length=2),
        ),
    ]
