# Generated by Django 5.0.3 on 2024-05-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MR', 'Mirinda'), ('MD', 'Mountain Dew'), ('SP', 'Sprite'), ('BS', 'Bisleri'), ('7U', '7UP'), ('FA', 'Fanta'), ('CO', 'Coca-Cola'), ('RB', 'Red Bull'), ('DR', 'Dr-Pepper'), ('PS', 'Pepsi')], max_length=2),
        ),
    ]
