# Generated by Django 5.0.3 on 2024-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SP', 'Sprite'), ('PS', 'Pepsi'), ('RB', 'Red Bull'), ('BS', 'Bisleri'), ('FA', 'Fanta'), ('CO', 'Coca-Cola'), ('7U', '7UP'), ('MD', 'Mountain Dew'), ('MR', 'Mirinda'), ('DR', 'Dr-Pepper')], max_length=2),
        ),
    ]
