# Generated by Django 5.0.3 on 2024-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DR', 'Dr-Pepper'), ('7U', '7UP'), ('RB', 'Red Bull'), ('CO', 'Coca-Cola'), ('FA', 'Fanta'), ('BS', 'Bisleri'), ('MD', 'Mountain Dew'), ('MR', 'Mirinda'), ('SP', 'Sprite'), ('PS', 'Pepsi')], max_length=2),
        ),
    ]
