# Generated by Django 5.0.3 on 2024-06-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FA', 'Fanta'), ('MR', 'Mirinda'), ('SP', 'Sprite'), ('7U', '7UP'), ('RB', 'Red Bull'), ('CO', 'Coca-Cola'), ('DR', 'Dr-Pepper'), ('BS', 'Bisleri'), ('PS', 'Pepsi'), ('MD', 'Mountain Dew')], max_length=2),
        ),
    ]
