# Generated by Django 5.0.3 on 2024-06-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CO', 'Coca-Cola'), ('MD', 'Mountain Dew'), ('SP', 'Sprite'), ('MR', 'Mirinda'), ('PS', 'Pepsi'), ('RB', 'Red Bull'), ('7U', '7UP'), ('FA', 'Fanta'), ('BS', 'Bisleri'), ('DR', 'Dr-Pepper')], max_length=2),
        ),
    ]
