# Generated by Django 5.0.3 on 2024-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MD', 'Mountain Dew'), ('MR', 'Mirinda'), ('DR', 'Dr-Pepper'), ('FA', 'Fanta'), ('CO', 'Coca-Cola'), ('7U', '7UP'), ('RB', 'Red Bull'), ('SP', 'Sprite'), ('PS', 'Pepsi'), ('BS', 'Bisleri')], max_length=2),
        ),
    ]
