# Generated by Django 5.0.3 on 2024-06-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RB', 'Red Bull'), ('7U', '7UP'), ('MR', 'Mirinda'), ('DR', 'Dr-Pepper'), ('BS', 'Bisleri'), ('CO', 'Coca-Cola'), ('FA', 'Fanta'), ('MD', 'Mountain Dew'), ('PS', 'Pepsi'), ('SP', 'Sprite')], max_length=2),
        ),
    ]
