# Generated by Django 5.0.3 on 2024-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MD', 'Mountain Dew'), ('DR', 'Dr-Pepper'), ('7U', '7UP'), ('SP', 'Sprite'), ('FA', 'Fanta'), ('PS', 'Pepsi'), ('CO', 'Coca-Cola'), ('RB', 'Red Bull'), ('MR', 'Mirinda'), ('BS', 'Bisleri')], max_length=2),
        ),
    ]
